USE app_db;


DROP TABLE IF EXISTS User_Assignments;
DROP TABLE IF EXISTS Assignments;
DROP TABLE IF EXISTS Files;
DROP TABLE IF EXISTS Notes;
DROP TABLE IF EXISTS Recurring_Tasks;
DROP TABLE IF EXISTS Schedules;
DROP TABLE IF EXISTS Time_Tables;
DROP TABLE IF EXISTS User_Courses;
DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS Users;
